//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ColumnsPlusPlus.rc
//
#define IDD_ELASTIC_TABSTOPS_PROFILE    103
#define IDD_SEARCH                      105
#define IDD_MORE                        107
#define IDD_OPTIONS                     108
#define IDD_ABOUT                       111
#define IDD_PROFILE_SAVE                117
#define IDD_PROFILE_RENAME              118
#define IDD_CALCULATION_RESULTS         120
#define IDD_CHOOSE_RECTANGULAR_SELECTION 122
#define IDD_CHOOSE_RECTANGULAR_SELECTION_HORIZONTAL 123
#define IDD_CHOOSE_RECTANGULAR_SELECTION_VERTICAL 124
#define IDD_CSV                         125
#define IDD_CALCULATE                   127
#define IDC_LINE_UP_ALL                 1003
#define IDC_LEADING_TABS_INDENT         1006
#define IDC_DISABLE_FILE_SIZE           1007
#define IDC_OVERRIDE_TAB_SIZE           1008
#define IDC_DISABLE_FILE_SIZE_VALUE     1009
#define IDC_DISABLE_FILE_LINES          1010
#define IDC_TREAT_EOL_AS_TAB            1011
#define IDC_DISABLE_FILE_LINES_VALUE    1012
#define IDC_MINIMUM_SPACE_VALUE         1018
#define IDC_DISABLE_FILE_TYPE           1020
#define IDC_ENABLE_NUMERIC_ALIGNMENT    1021
#define IDC_ENABLE_FILE_TYPE            1022
#define IDC_PROFILE_SELECT              1023
#define IDC_OVERRIDE_TAB_SIZE_VALUE     1024
#define IDC_OVERRIDE_TAB_SIZE_SPIN      1025
#define IDC_OPTIONS_INDICATOR_NUMBER    1026
#define IDC_OPTIONS_INDICATOR_NUMBER_SPIN 1027
#define IDC_MINIMUM_SPACE_SPIN          1028
#define IDC_OPTIONS_INDICATOR_ALPHA     1028
#define IDC_PROFILE_SAVE                1029
#define IDC_OPTIONS_INDICATOR_ALPHA_SPIN 1029
#define IDC_BUTTON2                     1030
#define IDC_PROFILE_MANAGER             1030
#define IDC_SEARCH_COUNT                1030
#define IDC_OPTIONS_INDICATOR_GREEN     1030
#define IDC_FIND_WHAT                   1031
#define IDC_OPTIONS_INDICATOR_GREEN_SPIN 1031
#define IDC_OPTIONS_INDICATOR_BLUE      1032
#define IDC_OVERRIDE_TAB_SIZE_SPIN5     1033
#define IDC_OPTIONS_INDICATOR_BLUE_SPIN 1033
#define IDC_SEARCH_REPLACE              1034
#define IDC_SEARCH_REPLACE_ALL          1035
#define IDC_SEARCH_BACKWARD             1036
#define IDC_SEARCH_WHOLE_WORD           1037
#define IDC_SEARCH_MATCH_CASE           1038
#define IDC_SEARCH_NORMAL               1040
#define IDC_SEARCH_EXTENDED             1041
#define IDC_SEARCH_REGEX                1042
#define IDC_REPLACE_WITH                1044
#define IDC_SEARCH_MESSAGE              1045
#define IDC_SCROLLBAR2                  1047
#define IDC_MENUBAR                     1049
#define IDC_MORE_MENUBAR                1049
#define IDC_OPTIONS_MENUBAR             1055
#define IDC_OPTIONS_REPLACE_STAY_PUT    1056
#define IDC_OPTIONS_REPLACE_STAYS_PUT   1056
#define IDC_ABOUT_HELP                  1057
#define IDC_ABOUT_MORE                  1058
#define IDC_ABOUT_VERSION               1059
#define IDC_OPTIONS_EXTEND_SINGLELINE   1060
#define IDC_OPTIONS_EXTEND_ROWS         1061
#define IDC_OPTIONS_EXTEND_ZEROWIDTH    1063
#define IDC_OPTIONS_EXTEND_BOX          1067
#define IDC_PROFILE_SAVE_NAME           1073
#define IDC_PROFILE_RENAME_NAME         1075
#define IDC_DEFAULT_KEEP                1076
#define IDC_DEFAULT_DISABLE             1077
#define IDC_DEFAULT_ENABLE              1078
#define IDC_COMBO1                      1079
#define IDC_DEFAULT_PROFILE             1079
#define IDC_SEARCH_INDICATOR            1079
#define IDC_CSV_REPLACE                 1079
#define IDC_CALCULATE_REGEX             1079
#define IDC_CALCULATION_RESULTS         1080
#define IDC_CALCULATION_MESSAGE         1082
#define IDC_THOUSANDS_NONE              1083
#define IDC_THOUSANDS_COMMA             1084
#define IDC_THOUSANDS_APOSTROPHE        1085
#define IDC_THOUSANDS_BLANK             1086
#define IDC_CALCULATION_INSERT          1087
#define IDC_SELECT_RECTANGULAR_UP       1088
#define IDC_SELECT_RECTANGULAR_ALL      1089
#define IDC_SELECT_RECTANGULAR_DOWN     1090
#define IDC_SELECT_RECTANGULAR_UPRIGHT  1091
#define IDC_SELECT_RECTANGULAR_RIGHT    1092
#define IDC_BUTTON7                     1093
#define IDC_SELECT_RECTANGULAR_DOWNRIGHT 1093
#define IDC_MAKE_A_RECT                 1094
#define IDC_SELECT_RECTANGULAR_UPLEFT   1095
#define IDC_SELECT_RECTANGULAR_LEFT     1096
#define IDC_SEARCH_INDICATOR_AUTOCLEAR  1096
#define IDC_SELECT_RECTANGULAR_DOWNLEFT 1097
#define IDC_SEARCH_INDICATOR_CLEARNOW   1097
#define IDC_OPTIONS_INDICATOR_ENABLED   1098
#define IDC_OPTIONS_INDICATOR_RED       1100
#define IDC_OPTIONS_INDICATOR_RED_SPIN  1101
#define IDC_CSV_COMMA                   1102
#define IDC_CSV_SEMICOLON               1103
#define IDC_CSV_VERTICAL_LINE           1104
#define IDC_CSV_OTHER_SEPARATOR_RADIO   1105
#define IDC_CSV_OTHER_SEPARATOR_EDIT    1106
#define IDC_CSV_QUOTE                   1107
#define IDC_CSV_APOSTROPHE              1108
#define IDC_CSV_PRESERVE_QUOTES_AND_ESCAPES 1109
#define IDC_CSV_PRESERVE_QUOTES         1109
#define IDC_CSV_TNR_EDIT                1110
#define IDC_CSV_ESCAPE_WITH_BACKSLASH   1111
#define IDC_CSV_ESCAPE_EDIT             1111
#define IDC_CSV_URL_EDIT                1112
#define IDC_CSV_BACKSLASH               1114
#define IDC_CSV_ESCAPE_CHECK            1114
#define IDC_CSV_TNR_RADIO               1115
#define IDC_URL_RADIO                   1116
#define IDC_CSV_URL_RADIO               1116
#define IDC_CSV_REPLACE_TAB             1118
#define IDC_CSV_REPLACE_LF              1119
#define IDC_MONOSPACED_BEST             1119
#define IDC_CSV_REPLACE_CR              1120
#define IDC_MONOSPACED_YES              1120
#define IDC_MONOSPACED_NO               1121
#define IDC_CHECK1                      1122
#define IDC_MONOSPACED_RENDER           1122
#define IDC_CALCULATE_MATCH_CASE        1122
#define IDC_CALCULATE_FORMULA           1127
#define IDC_CALCULATE_PLACES_EDIT       1130
#define IDC_CALCULATE_PLACES_SPIN       1131
#define IDC_CALCULATE_TIME_MINUTES      1135
#define IDC_CALCULATE_TIME_DAYS         1136
#define IDC_CALCULATE_SKIP_UNMATCHED    1138
#define IDC_CALCULATE_TIME              1143
#define IDC_CALCULATE_TABBED            1144
#define IDC_CALCULATE_ALIGNED           1146
#define IDC_CALCULATE_SUPPRESS_ZEROS    1147
#define IDC_CHECK2                      1148
#define IDC_CALCULATE_LEFT              1148

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1149
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
